project_name: pscale-proxy
release:
  prerelease: auto # don't publish release with -rc1,-pre, etc suffixes
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/sql-proxy-client/main.go
    ldflags:
     - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    binary: "pscale-proxy"   
dockers:
  - image_templates:
    - "planetscale/pscale-proxy:latest"
    - "planetscale/pscale-proxy:{{ .Tag }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    dockerfile: Dockerfile.goreleaser
nfpms:
  - maintainer: PlanetScale
    description: The PlanetScale SQL Proxy
    homepage: https://github.com/planetscale/sql-proxy
    license: Apache 2.0
    formats:
    - deb
    - rpm
    replacements:
      darwin: macOS
brews:
  - homepage: "https://planetscale.com/"
    description: "The PlanetScale SQL Proxy"
    name: "pscale-proxy"
    license: Apache 2.0
    tap: 
      owner: planetscale
      name: homebrew-tap
    folder: Formula
    test: |
         system "#{bin}/pscale-proxy --version"
    install: |
      bin.install "pscale-proxy"
archives:
  - replacements:
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: "{{ .Tag }}-next"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
